spring.application.name=student-service
server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/db_student_profile
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
notification.tcp.host=localhost
notification.tcp.port=9090
spring.jackson.deserialization.fail-on-unknown-properties=true